import json, os

EX = {
  "1": [
    {"unit":"Unidade 1","rubric":"Complete with am, is or are.","question":"I {{c1::am}} a software engineer.","choices":[]},
    {"unit":"Unidade 1","rubric":"Complete with am, is or are.","question":"She {{c1::is}} the project manager.","choices":[]},
    {"unit":"Unidade 1","rubric":"Complete with am, is or are.","question":"We {{c1::are}} ready for the presentation.","choices":[]},
    {"unit":"Unidade 1","rubric":"Complete with am, is or are.","question":"The servers {{c1::are}} down at the moment.","choices":[]},
    {"unit":"Unidade 1","rubric":"Complete with am, is or are.","question":"It {{c1::is}} a very complex problem.","choices":[]},
    {"unit":"Unidade 1","rubric":"Complete with am, is or are.","question":"They {{c1::are}} from Portugal.","choices":[]},
  ],
  "2": [
    {"unit":"Unidade 2","rubric":"Complete the question with Am, Is or Are.","question":"{{c1::Are}} you from Portugal?","choices":[]},
    {"unit":"Unidade 2","rubric":"Complete the question with Am, Is or Are.","question":"{{c1::Is}} she the new manager?","choices":[]},
    {"unit":"Unidade 2","rubric":"Complete the question with Am, Is or Are.","question":"Where {{c1::are}} they from?","choices":[]},
    {"unit":"Unidade 2","rubric":"Complete the question with Am, Is or Are.","question":"{{c1::Is}} this your bag?","choices":[]},
    {"unit":"Unidade 2","rubric":"Complete the question with Am, Is or Are.","question":"How old {{c1::are}} you?","choices":[]},
    {"unit":"Unidade 2","rubric":"Complete the question with Am, Is or Are.","question":"{{c1::Am}} I late for the meeting?","choices":[]},
  ],
  "9": [
    {"unit":"Unidade 9","rubric":"Complete with have/has or have got/has got.","question":"I {{c1::have}} a meeting at 10.","choices":[]},
    {"unit":"Unidade 9","rubric":"Complete with have/has or have got/has got.","question":"She {{c1::has got}} two cats.","choices":[]},
    {"unit":"Unidade 9","rubric":"Complete with have/has or have got/has got.","question":"{{c1::Have}} you got a pen?","choices":[]},
    {"unit":"Unidade 9","rubric":"Complete with have/has or have got/has got.","question":"He {{c1::hasn't got}} time right now.","choices":[]},
    {"unit":"Unidade 9","rubric":"Complete with have/has or have got/has got.","question":"They {{c1::have}} a big office downtown.","choices":[]},
    {"unit":"Unidade 9","rubric":"Complete with have/has or have got/has got.","question":"We {{c1::haven't}} got any coffee left.","choices":[]},
  ],
  "21": [
    {"unit":"Unidade 21","rubric":"Complete with the correct passive form (is/are + past participle).","question":"English {{c1::is spoken}} all over the world.","choices":[]},
    {"unit":"Unidade 21","rubric":"Complete with the correct passive form (was/were + past participle).","question":"This bridge {{c1::was built}} in 1902.","choices":[]},
    {"unit":"Unidade 21","rubric":"Complete with the correct passive form.","question":"The letter {{c1::was written}} by the CEO.","choices":[]},
    {"unit":"Unidade 21","rubric":"Complete with the correct passive form.","question":"These cars {{c1::are made}} in Japan.","choices":[]},
    {"unit":"Unidade 21","rubric":"Complete with the correct passive form.","question":"My bike {{c1::was stolen}} last night.","choices":[]},
    {"unit":"Unidade 21","rubric":"Complete with the correct passive form.","question":"The report {{c1::is sent}} every Friday.","choices":[]},
  ],
  "22": [
    {"unit":"Unidade 22","rubric":"Complete with the correct passive form (is/are being or has/have been + past participle).","question":"The office {{c1::is being renovated}} this week.","choices":[]},
    {"unit":"Unidade 22","rubric":"Complete with the correct passive form.","question":"The documents {{c1::have been sent}} to the client.","choices":[]},
    {"unit":"Unidade 22","rubric":"Complete with the correct passive form.","question":"A new system {{c1::is being developed}} by the team.","choices":[]},
    {"unit":"Unidade 22","rubric":"Complete with the correct passive form.","question":"The bug {{c1::has been fixed}} by the developers.","choices":[]},
    {"unit":"Unidade 22","rubric":"Complete with the correct passive form.","question":"The website {{c1::is being updated}} right now.","choices":[]},
    {"unit":"Unidade 22","rubric":"Complete with the correct passive form.","question":"All the data {{c1::has been backed up}} successfully.","choices":[]},
  ],
  "23": [
    {"unit":"Unidade 23","rubric":"Complete with the correct form of be, have or do.","question":"She {{c1::does}} her homework every evening.","choices":[]},
    {"unit":"Unidade 23","rubric":"Complete with the correct form of be, have or do.","question":"They {{c1::were}} at the conference yesterday.","choices":[]},
    {"unit":"Unidade 23","rubric":"Complete with the correct form of be, have or do.","question":"He {{c1::has}} finished the project.","choices":[]},
    {"unit":"Unidade 23","rubric":"Complete with the correct form of be, have or do.","question":"{{c1::Do}} you speak English?","choices":[]},
    {"unit":"Unidade 23","rubric":"Complete with the correct form of be, have or do.","question":"I {{c1::was}} busy all day yesterday.","choices":[]},
    {"unit":"Unidade 23","rubric":"Complete with the correct form of be, have or do.","question":"We {{c1::are}} having a meeting now.","choices":[]},
  ],
  "24": [
    {"unit":"Unidade 24","rubric":"Write the past simple form of the verb.","question":"go → {{c1::went}}","choices":[]},
    {"unit":"Unidade 24","rubric":"Write the past simple form of the verb.","question":"buy → {{c1::bought}}","choices":[]},
    {"unit":"Unidade 24","rubric":"Write the past simple form of the verb.","question":"speak → {{c1::spoke}}","choices":[]},
    {"unit":"Unidade 24","rubric":"Write the past simple form of the verb.","question":"work → {{c1::worked}}","choices":[]},
    {"unit":"Unidade 24","rubric":"Write the past simple form of the verb.","question":"write → {{c1::wrote}}","choices":[]},
    {"unit":"Unidade 24","rubric":"Write the past simple form of the verb.","question":"finish → {{c1::finished}}","choices":[]},
    {"unit":"Unidade 24","rubric":"Write the past simple form of the verb.","question":"take → {{c1::took}}","choices":[]},
    {"unit":"Unidade 24","rubric":"Write the past simple form of the verb.","question":"send → {{c1::sent}}","choices":[]},
  ],
  "27": [
    {"unit":"Unidade 27","rubric":"Complete with will or won't.","question":"I think it {{c1::will}} rain tomorrow.","choices":[]},
    {"unit":"Unidade 27","rubric":"Complete with will or won't.","question":"Don't worry, I {{c1::will}} help you.","choices":[]},
    {"unit":"Unidade 27","rubric":"Complete with will or won't.","question":"She {{c1::won't}} be at the meeting — she's away.","choices":[]},
    {"unit":"Unidade 27","rubric":"Complete with will or won't.","question":"{{c1::Will}} you be free on Friday?","choices":[]},
    {"unit":"Unidade 27","rubric":"Complete with will or won't.","question":"The project {{c1::won't}} be ready by Monday.","choices":[]},
    {"unit":"Unidade 27","rubric":"Complete with will or won't.","question":"I promise I {{c1::will}} call you later.","choices":[]},
  ],
  "28": [
    {"unit":"Unidade 28","rubric":"Complete with will or shall.","question":"{{c1::Shall}} I open the window?","choices":[]},
    {"unit":"Unidade 28","rubric":"Complete with will or shall.","question":"What time {{c1::shall}} we meet?","choices":[]},
    {"unit":"Unidade 28","rubric":"Complete with will or shall.","question":"{{c1::Shall}} we go for lunch?","choices":[]},
    {"unit":"Unidade 28","rubric":"Complete with will or shall.","question":"Don't call me — I {{c1::will}} call you.","choices":[]},
    {"unit":"Unidade 28","rubric":"Complete with will or shall.","question":"{{c1::Shall}} I carry that bag for you?","choices":[]},
  ],
  "29": [
    {"unit":"Unidade 29","rubric":"Complete with might or might not.","question":"I {{c1::might}} be late — it depends on traffic.","choices":[]},
    {"unit":"Unidade 29","rubric":"Complete with might or might not.","question":"She {{c1::might not}} come to the party.","choices":[]},
    {"unit":"Unidade 29","rubric":"Complete with might or might not.","question":"It {{c1::might}} rain this afternoon — take an umbrella.","choices":[]},
    {"unit":"Unidade 29","rubric":"Complete with might or might not.","question":"He {{c1::might}} have the answer — try asking him.","choices":[]},
    {"unit":"Unidade 29","rubric":"Complete with might or might not.","question":"They {{c1::might not}} accept the offer.","choices":[]},
    {"unit":"Unidade 29","rubric":"Complete with might or might not.","question":"I'm not sure — I {{c1::might}} work from home tomorrow.","choices":[]},
  ],
  "32": [
    {"unit":"Unidade 32","rubric":"Complete with should or shouldn't.","question":"You {{c1::should}} see a doctor if you're ill.","choices":[]},
    {"unit":"Unidade 32","rubric":"Complete with should or shouldn't.","question":"We {{c1::shouldn't}} be late for the presentation.","choices":[]},
    {"unit":"Unidade 32","rubric":"Complete with should or shouldn't.","question":"He {{c1::should}} apologise for his mistake.","choices":[]},
    {"unit":"Unidade 32","rubric":"Complete with should or shouldn't.","question":"You {{c1::shouldn't}} eat so much sugar.","choices":[]},
    {"unit":"Unidade 32","rubric":"Complete with should or shouldn't.","question":"I think she {{c1::should}} apply for the job.","choices":[]},
    {"unit":"Unidade 32","rubric":"Complete with should or shouldn't.","question":"They {{c1::shouldn't}} work such long hours.","choices":[]},
  ],
  "33": [
    {"unit":"Unidade 33","rubric":"Complete with have to, has to, don't have to or doesn't have to.","question":"I {{c1::have to}} finish this report by Friday.","choices":[]},
    {"unit":"Unidade 33","rubric":"Complete with have to, has to, don't have to or doesn't have to.","question":"She {{c1::has to}} attend the meeting.","choices":[]},
    {"unit":"Unidade 33","rubric":"Complete with have to, has to, don't have to or doesn't have to.","question":"You {{c1::don't have to}} wear a tie — it's casual Friday.","choices":[]},
    {"unit":"Unidade 33","rubric":"Complete with have to, has to, don't have to or doesn't have to.","question":"He {{c1::doesn't have to}} work on weekends.","choices":[]},
    {"unit":"Unidade 33","rubric":"Complete with have to, has to, don't have to or doesn't have to.","question":"We {{c1::have to}} update the system tonight.","choices":[]},
    {"unit":"Unidade 33","rubric":"Complete with have to, has to, don't have to or doesn't have to.","question":"They {{c1::have to}} sign the contract today.","choices":[]},
  ],
  "34": [
    {"unit":"Unidade 34","rubric":"Complete with would like or 'd like.","question":"{{c1::Would you like}} a coffee?","choices":[]},
    {"unit":"Unidade 34","rubric":"Complete with would like or 'd like.","question":"I {{c1::would like}} to book a table for two.","choices":[]},
    {"unit":"Unidade 34","rubric":"Complete with would like or 'd like.","question":"{{c1::Would you like}} me to send the file?","choices":[]},
    {"unit":"Unidade 34","rubric":"Complete with would like or 'd like.","question":"She {{c1::would like}} to work remotely.","choices":[]},
    {"unit":"Unidade 34","rubric":"Complete with would like or 'd like.","question":"{{c1::Would you like}} some help with that?","choices":[]},
    {"unit":"Unidade 34","rubric":"Complete with would like or 'd like.","question":"I {{c1::would like}} some more information, please.","choices":[]},
  ],
  "35": [
    {"unit":"Unidade 35","rubric":"Complete the imperative or suggestion with the correct form.","question":"{{c1::Don't}} use your phone during the meeting.","choices":[]},
    {"unit":"Unidade 35","rubric":"Complete the imperative or suggestion with the correct form.","question":"{{c1::Let's}} discuss this tomorrow.","choices":[]},
    {"unit":"Unidade 35","rubric":"Complete the imperative or suggestion with the correct form.","question":"{{c1::Send}} me the report as soon as possible.","choices":[]},
    {"unit":"Unidade 35","rubric":"Complete the imperative or suggestion with the correct form.","question":"{{c1::Don't}} be late.","choices":[]},
    {"unit":"Unidade 35","rubric":"Complete the imperative or suggestion with the correct form.","question":"{{c1::Let's}} take a break — we've been working for three hours.","choices":[]},
    {"unit":"Unidade 35","rubric":"Complete the imperative or suggestion with the correct form.","question":"{{c1::Close}} the door, please.","choices":[]},
  ],
  "36": [
    {"unit":"Unidade 36","rubric":"Complete with used to or didn't use to.","question":"I {{c1::used to}} live in London.","choices":[]},
    {"unit":"Unidade 36","rubric":"Complete with used to or didn't use to.","question":"She {{c1::didn't use to}} like coffee, but now she loves it.","choices":[]},
    {"unit":"Unidade 36","rubric":"Complete with used to or didn't use to.","question":"He {{c1::used to}} work for a large company.","choices":[]},
    {"unit":"Unidade 36","rubric":"Complete with used to or didn't use to.","question":"We {{c1::used to}} have meetings every day.","choices":[]},
    {"unit":"Unidade 36","rubric":"Complete with used to or didn't use to.","question":"She {{c1::used to}} be very shy.","choices":[]},
    {"unit":"Unidade 36","rubric":"Complete with used to or didn't use to.","question":"I {{c1::didn't use to}} exercise regularly.","choices":[]},
  ],
  "37": [
    {"unit":"Unidade 37","rubric":"Complete with there is or there are.","question":"{{c1::There is}} a problem with the server.","choices":[]},
    {"unit":"Unidade 37","rubric":"Complete with there is or there are.","question":"{{c1::There are}} ten people in the team.","choices":[]},
    {"unit":"Unidade 37","rubric":"Complete with Is there or Are there.","question":"{{c1::Is there}} any coffee left?","choices":[]},
    {"unit":"Unidade 37","rubric":"Complete with there is or there are.","question":"{{c1::There are}} no meetings today.","choices":[]},
    {"unit":"Unidade 37","rubric":"Complete with there is or there are.","question":"{{c1::There is}} a new update available.","choices":[]},
    {"unit":"Unidade 37","rubric":"Complete with Is there or Are there.","question":"{{c1::Are there}} any questions?","choices":[]},
  ],
  "38": [
    {"unit":"Unidade 38","rubric":"Complete with there was, there were, there has been or there have been.","question":"{{c1::There was}} a power cut last night.","choices":[]},
    {"unit":"Unidade 38","rubric":"Complete with there was, there were, there has been or there have been.","question":"{{c1::There were}} many people at the conference.","choices":[]},
    {"unit":"Unidade 38","rubric":"Complete with there was, there were, there has been or there have been.","question":"{{c1::There has been}} a change in the schedule.","choices":[]},
    {"unit":"Unidade 38","rubric":"Complete with there was, there were, there has been or there have been.","question":"{{c1::There have been}} several complaints this week.","choices":[]},
    {"unit":"Unidade 38","rubric":"Complete with Was there or Were there.","question":"{{c1::Was there}} a meeting yesterday?","choices":[]},
    {"unit":"Unidade 38","rubric":"Complete with there was, there were, there has been or there have been.","question":"{{c1::There were}} no seats left on the train.","choices":[]},
  ],
  "39": [
    {"unit":"Unidade 39","rubric":"Complete with It is, It was or It takes.","question":"{{c1::It}} is very cold today.","choices":[]},
    {"unit":"Unidade 39","rubric":"Complete with It is, It was or It takes.","question":"{{c1::It}} takes about 30 minutes to get to the office.","choices":[]},
    {"unit":"Unidade 39","rubric":"Complete with It is, It was or It takes.","question":"{{c1::It}} was a very long meeting.","choices":[]},
    {"unit":"Unidade 39","rubric":"Complete with It is, It was or It takes.","question":"{{c1::It}} is difficult to learn a new language.","choices":[]},
    {"unit":"Unidade 39","rubric":"Complete with It is, It was or It takes.","question":"{{c1::It}} is important to communicate clearly.","choices":[]},
    {"unit":"Unidade 39","rubric":"Complete with It is, It was or It takes.","question":"{{c1::It}} takes courage to make that decision.","choices":[]},
  ],
  "40": [
    {"unit":"Unidade 40","rubric":"Complete the short answer with the correct auxiliary.","question":"Are you ready? — Yes, I {{c1::am}}.","choices":[]},
    {"unit":"Unidade 40","rubric":"Complete the short answer with the correct auxiliary.","question":"Does she work here? — No, she {{c1::doesn't}}.","choices":[]},
    {"unit":"Unidade 40","rubric":"Complete the short answer with the correct auxiliary.","question":"Have they arrived? — Yes, they {{c1::have}}.","choices":[]},
    {"unit":"Unidade 40","rubric":"Complete the short answer with the correct auxiliary.","question":"Was he at the meeting? — No, he {{c1::wasn't}}.","choices":[]},
    {"unit":"Unidade 40","rubric":"Complete the short answer with the correct auxiliary.","question":"Did you finish? — Yes, I {{c1::did}}.","choices":[]},
    {"unit":"Unidade 40","rubric":"Complete the short answer with the correct auxiliary.","question":"Can she help? — No, she {{c1::can't}}.","choices":[]},
  ],
  "41": [
    {"unit":"Unidade 41","rubric":"Add the correct question tag.","question":"You're a developer, {{c1::aren't you}}?","choices":[]},
    {"unit":"Unidade 41","rubric":"Add the correct question tag.","question":"She hasn't called yet, {{c1::has she}}?","choices":[]},
    {"unit":"Unidade 41","rubric":"Add the correct question tag.","question":"They finished the project, {{c1::didn't they}}?","choices":[]},
    {"unit":"Unidade 41","rubric":"Add the correct question tag.","question":"It's a great idea, {{c1::isn't it}}?","choices":[]},
    {"unit":"Unidade 41","rubric":"Add the correct question tag.","question":"You've been here before, {{c1::haven't you}}?","choices":[]},
    {"unit":"Unidade 41","rubric":"Add the correct question tag.","question":"He doesn't know, {{c1::does he}}?","choices":[]},
  ],
  "42": [
    {"unit":"Unidade 42","rubric":"Complete with too, either, so or neither.","question":"I'm tired. — {{c1::So am I}}.","choices":[]},
    {"unit":"Unidade 42","rubric":"Complete with too, either, so or neither.","question":"She doesn't like Mondays. — {{c1::Neither do I}}.","choices":[]},
    {"unit":"Unidade 42","rubric":"Complete with too, either, so or neither.","question":"He can swim. — I can {{c1::too}}.","choices":[]},
    {"unit":"Unidade 42","rubric":"Complete with too, either, so or neither.","question":"I haven't finished. — {{c1::Neither have I}}.","choices":[]},
    {"unit":"Unidade 42","rubric":"Complete with too, either, so or neither.","question":"We're leaving now. — {{c1::So are we}}.","choices":[]},
    {"unit":"Unidade 42","rubric":"Complete with too, either, so or neither.","question":"He didn't come. — She didn't {{c1::either}}.","choices":[]},
  ],
  "43": [
    {"unit":"Unidade 43","rubric":"Make these sentences negative.","question":"She is at work. → She {{c1::isn't}} at work.","choices":[]},
    {"unit":"Unidade 43","rubric":"Make these sentences negative.","question":"They have finished. → They {{c1::haven't}} finished.","choices":[]},
    {"unit":"Unidade 43","rubric":"Make these sentences negative.","question":"He speaks French. → He {{c1::doesn't}} speak French.","choices":[]},
    {"unit":"Unidade 43","rubric":"Make these sentences negative.","question":"I was there. → I {{c1::wasn't}} there.","choices":[]},
    {"unit":"Unidade 43","rubric":"Make these sentences negative.","question":"We can help. → We {{c1::can't}} help.","choices":[]},
    {"unit":"Unidade 43","rubric":"Make these sentences negative.","question":"She will come. → She {{c1::won't}} come.","choices":[]},
  ],
  "44": [
    {"unit":"Unidade 44","rubric":"Form the question correctly.","question":"(where / she / live) → {{c1::Where does she live?}}","choices":[]},
    {"unit":"Unidade 44","rubric":"Form the question correctly.","question":"(what / you / do) → {{c1::What do you do?}}","choices":[]},
    {"unit":"Unidade 44","rubric":"Form the question correctly.","question":"(when / he / arrive) → {{c1::When did he arrive?}}","choices":[]},
    {"unit":"Unidade 44","rubric":"Form the question correctly.","question":"(how / they / travel) → {{c1::How do they travel?}}","choices":[]},
    {"unit":"Unidade 44","rubric":"Form the question correctly.","question":"(what / she / study) → {{c1::What does she study?}}","choices":[]},
    {"unit":"Unidade 44","rubric":"Form the question correctly.","question":"(where / you / work) → {{c1::Where do you work?}}","choices":[]},
  ],
  "45": [
    {"unit":"Unidade 45","rubric":"Is who the subject or the object? Form the correct question.","question":"Somebody called you. → {{c1::Who called you?}}","choices":[]},
    {"unit":"Unidade 45","rubric":"Is who the subject or the object? Form the correct question.","question":"You called somebody. → {{c1::Who did you call?}}","choices":[]},
    {"unit":"Unidade 45","rubric":"Is who the subject or the object? Form the correct question.","question":"Somebody helped him. → {{c1::Who helped him?}}","choices":[]},
    {"unit":"Unidade 45","rubric":"Is who the subject or the object? Form the correct question.","question":"He helped somebody. → {{c1::Who did he help?}}","choices":[]},
    {"unit":"Unidade 45","rubric":"Is what the subject or the object? Form the correct question.","question":"Something happened. → {{c1::What happened?}}","choices":[]},
    {"unit":"Unidade 45","rubric":"Is what the subject or the object? Form the correct question.","question":"She did something. → {{c1::What did she do?}}","choices":[]},
  ],
  "46": [
    {"unit":"Unidade 46","rubric":"Form the question. Put the preposition at the end.","question":"She's waiting for something. → {{c1::What is she waiting for?}}","choices":[]},
    {"unit":"Unidade 46","rubric":"Form the question. Put the preposition at the end.","question":"He's talking to someone. → {{c1::Who is he talking to?}}","choices":[]},
    {"unit":"Unidade 46","rubric":"Form the question. Put the preposition at the end.","question":"She works with someone. → {{c1::Who does she work with?}}","choices":[]},
    {"unit":"Unidade 46","rubric":"Form the question. Put the preposition at the end.","question":"He's thinking about something. → {{c1::What is he thinking about?}}","choices":[]},
    {"unit":"Unidade 46","rubric":"Form the question. Put the preposition at the end.","question":"She comes from somewhere. → {{c1::Where does she come from?}}","choices":[]},
  ],
  "47": [
    {"unit":"Unidade 47","rubric":"Complete the question with What, Which or How.","question":"{{c1::What}} is your job?","choices":[]},
    {"unit":"Unidade 47","rubric":"Complete the question with What, Which or How.","question":"{{c1::Which}} bus goes to the city centre?","choices":[]},
    {"unit":"Unidade 47","rubric":"Complete the question with What, Which or How.","question":"{{c1::How}} far is the station?","choices":[]},
    {"unit":"Unidade 47","rubric":"Complete the question with What, Which or How.","question":"{{c1::What}} time does the meeting start?","choices":[]},
    {"unit":"Unidade 47","rubric":"Complete the question with What, Which or How.","question":"{{c1::Which}} option do you prefer — this one or that one?","choices":[]},
    {"unit":"Unidade 47","rubric":"Complete the question with What, Which or How.","question":"{{c1::How}} long have you been waiting?","choices":[]},
  ],
  "48": [
    {"unit":"Unidade 48","rubric":"Complete with How long does it take or How long did it take.","question":"{{c1::How long does it take}} to get to the airport from here?","choices":[]},
    {"unit":"Unidade 48","rubric":"Complete with How long does it take or How long did it take.","question":"{{c1::How long did it take}} to fix the problem?","choices":[]},
    {"unit":"Unidade 48","rubric":"Complete the answer with takes or took.","question":"It {{c1::takes}} about an hour by train.","choices":[]},
    {"unit":"Unidade 48","rubric":"Complete the answer with takes or took.","question":"It {{c1::took}} three days to finish the report.","choices":[]},
    {"unit":"Unidade 48","rubric":"Complete with How long does it take.","question":"{{c1::How long does it take}} to learn English?","choices":[]},
  ],
  "49": [
    {"unit":"Unidade 49","rubric":"Rewrite as an indirect question.","question":"Where does she work? → Do you know {{c1::where she works}}?","choices":[]},
    {"unit":"Unidade 49","rubric":"Rewrite as an indirect question.","question":"What time is it? → Can you tell me {{c1::what time it is}}?","choices":[]},
    {"unit":"Unidade 49","rubric":"Rewrite as an indirect question.","question":"When did he leave? → Do you know {{c1::when he left}}?","choices":[]},
    {"unit":"Unidade 49","rubric":"Rewrite as an indirect question.","question":"How much does it cost? → Do you know {{c1::how much it costs}}?","choices":[]},
    {"unit":"Unidade 49","rubric":"Rewrite as an indirect question.","question":"Where are my keys? → Do you know {{c1::where my keys are}}?","choices":[]},
  ],
  "53": [
    {"unit":"Unidade 53","rubric":"Complete with verb + object + to-infinitive.","question":"She wants me {{c1::to help}} her with the project.","choices":[]},
    {"unit":"Unidade 53","rubric":"Complete with verb + object + to-infinitive.","question":"He told us {{c1::to wait}} outside.","choices":[]},
    {"unit":"Unidade 53","rubric":"Complete with verb + object + to-infinitive.","question":"I'd like you {{c1::to send}} the report today.","choices":[]},
    {"unit":"Unidade 53","rubric":"Complete with verb + object + to-infinitive.","question":"They asked us {{c1::to attend}} the meeting.","choices":[]},
    {"unit":"Unidade 53","rubric":"Complete with verb + object + to-infinitive.","question":"She expected him {{c1::to call}} back immediately.","choices":[]},
    {"unit":"Unidade 53","rubric":"Complete with verb + object + to-infinitive.","question":"He advised me {{c1::to apply}} for the job.","choices":[]},
  ],
  "54": [
    {"unit":"Unidade 54","rubric":"Complete with to + infinitive to express purpose.","question":"I went to the supermarket {{c1::to buy}} some food.","choices":[]},
    {"unit":"Unidade 54","rubric":"Complete with to + infinitive to express purpose.","question":"She called me {{c1::to ask}} a question.","choices":[]},
    {"unit":"Unidade 54","rubric":"Complete with to + infinitive to express purpose.","question":"He went online {{c1::to check}} his emails.","choices":[]},
    {"unit":"Unidade 54","rubric":"Complete with to + infinitive to express purpose.","question":"We stayed late {{c1::to finish}} the project.","choices":[]},
    {"unit":"Unidade 54","rubric":"Complete with to + infinitive to express purpose.","question":"I'm saving money {{c1::to buy}} a new laptop.","choices":[]},
    {"unit":"Unidade 54","rubric":"Complete with to + infinitive to express purpose.","question":"She studied hard {{c1::to pass}} the exam.","choices":[]},
  ],
  "55": [
    {"unit":"Unidade 55","rubric":"Complete with go + -ing.","question":"We {{c1::went swimming}} at the beach last Sunday.","choices":[]},
    {"unit":"Unidade 55","rubric":"Complete with go + -ing.","question":"She {{c1::goes running}} every morning before work.","choices":[]},
    {"unit":"Unidade 55","rubric":"Complete with go + -ing.","question":"They {{c1::went shopping}} on Saturday afternoon.","choices":[]},
    {"unit":"Unidade 55","rubric":"Complete with go + -ing.","question":"Do you want to {{c1::go cycling}} this weekend?","choices":[]},
    {"unit":"Unidade 55","rubric":"Complete with go + -ing.","question":"He {{c1::goes skiing}} every winter.","choices":[]},
    {"unit":"Unidade 55","rubric":"Complete with go + -ing.","question":"We {{c1::went hiking}} in the mountains last summer.","choices":[]},
  ],
  "56": [
    {"unit":"Unidade 56","rubric":"Complete with the correct form of get.","question":"What time do you {{c1::get up}} in the morning?","choices":[]},
    {"unit":"Unidade 56","rubric":"Complete with the correct form of get.","question":"I {{c1::got}} home at 7 o'clock yesterday.","choices":[]},
    {"unit":"Unidade 56","rubric":"Complete with the correct form of get.","question":"She {{c1::is getting}} better — she was ill last week.","choices":[]},
    {"unit":"Unidade 56","rubric":"Complete with the correct form of get.","question":"They {{c1::got}} married last year.","choices":[]},
    {"unit":"Unidade 56","rubric":"Complete with the correct form of get.","question":"I couldn't {{c1::get}} into the system — wrong password.","choices":[]},
    {"unit":"Unidade 56","rubric":"Complete with the correct form of get.","question":"He {{c1::got}} a promotion last month.","choices":[]},
  ],
  "57": [
    {"unit":"Unidade 57","rubric":"Complete with do or make.","question":"Can you {{c1::do}} me a favour?","choices":[]},
    {"unit":"Unidade 57","rubric":"Complete with do or make.","question":"She {{c1::made}} a mistake in the report.","choices":[]},
    {"unit":"Unidade 57","rubric":"Complete with do or make.","question":"I need to {{c1::do}} some work this weekend.","choices":[]},
    {"unit":"Unidade 57","rubric":"Complete with do or make.","question":"He {{c1::makes}} a lot of money in his new job.","choices":[]},
    {"unit":"Unidade 57","rubric":"Complete with do or make.","question":"{{c1::Do}} your best!","choices":[]},
    {"unit":"Unidade 57","rubric":"Complete with do or make.","question":"Let's {{c1::make}} a decision now.","choices":[]},
    {"unit":"Unidade 57","rubric":"Complete with do or make.","question":"She {{c1::does}} the washing up every evening.","choices":[]},
    {"unit":"Unidade 57","rubric":"Complete with do or make.","question":"I need to {{c1::make}} a phone call.","choices":[]},
  ],
  "58": [
    {"unit":"Unidade 58","rubric":"Complete with the correct form of have.","question":"Let's {{c1::have}} a meeting tomorrow.","choices":[]},
    {"unit":"Unidade 58","rubric":"Complete with the correct form of have.","question":"She {{c1::has}} a shower every morning.","choices":[]},
    {"unit":"Unidade 58","rubric":"Complete with the correct form of have.","question":"We {{c1::had}} lunch together yesterday.","choices":[]},
    {"unit":"Unidade 58","rubric":"Complete with the correct form of have.","question":"{{c1::Have}} a look at this report.","choices":[]},
    {"unit":"Unidade 58","rubric":"Complete with the correct form of have.","question":"I {{c1::had}} a great time at the conference.","choices":[]},
    {"unit":"Unidade 58","rubric":"Complete with the correct form of have.","question":"They {{c1::have}} a coffee break at 11.","choices":[]},
  ],
  "59": [
    {"unit":"Unidade 59","rubric":"Choose the correct object pronoun.","question":"This is for {{c1::him}} — give it to him, not her.","choices":[]},
    {"unit":"Unidade 59","rubric":"Choose the correct object pronoun.","question":"She called {{c1::me}} this morning.","choices":[]},
    {"unit":"Unidade 59","rubric":"Choose the correct object pronoun.","question":"We saw {{c1::them}} at the conference.","choices":[]},
    {"unit":"Unidade 59","rubric":"Choose the correct object pronoun.","question":"Can you help {{c1::us}} with this?","choices":[]},
    {"unit":"Unidade 59","rubric":"Choose the correct object pronoun.","question":"I sent the report to {{c1::her}}.","choices":[]},
    {"unit":"Unidade 59","rubric":"Choose the correct object pronoun.","question":"Tell {{c1::him}} to call me back.","choices":[]},
  ],
  "60": [
    {"unit":"Unidade 60","rubric":"Complete with the correct possessive adjective (my/his/her/its/our/their).","question":"She forgot {{c1::her}} password again.","choices":[]},
    {"unit":"Unidade 60","rubric":"Complete with the correct possessive adjective.","question":"They submitted {{c1::their}} report on time.","choices":[]},
    {"unit":"Unidade 60","rubric":"Complete with the correct possessive adjective.","question":"I left {{c1::my}} phone in the meeting room.","choices":[]},
    {"unit":"Unidade 60","rubric":"Complete with the correct possessive adjective.","question":"He finished {{c1::his}} presentation early.","choices":[]},
    {"unit":"Unidade 60","rubric":"Complete with the correct possessive adjective.","question":"We need to update {{c1::our}} website.","choices":[]},
    {"unit":"Unidade 60","rubric":"Complete with the correct possessive adjective.","question":"The company closed {{c1::its}} offices downtown.","choices":[]},
  ],
  "64": [
    {"unit":"Unidade 64","rubric":"Rewrite using 's.","question":"the office of the manager → {{c1::the manager's office}}","choices":[]},
    {"unit":"Unidade 64","rubric":"Rewrite using 's.","question":"the car of my boss → {{c1::my boss's car}}","choices":[]},
    {"unit":"Unidade 64","rubric":"Rewrite using 's.","question":"the phone of Sarah → {{c1::Sarah's phone}}","choices":[]},
    {"unit":"Unidade 64","rubric":"Rewrite using 's.","question":"the report of James → {{c1::James's report}}","choices":[]},
    {"unit":"Unidade 64","rubric":"Rewrite using 's.","question":"the dog of the neighbour → {{c1::the neighbour's dog}}","choices":[]},
    {"unit":"Unidade 64","rubric":"Rewrite using 's.","question":"the house of my parents → {{c1::my parents' house}}","choices":[]},
  ],
  "65": [
    {"unit":"Unidade 65","rubric":"Complete with a or an.","question":"She is {{c1::a}} software engineer.","choices":[]},
    {"unit":"Unidade 65","rubric":"Complete with a or an.","question":"He has {{c1::an}} idea.","choices":[]},
    {"unit":"Unidade 65","rubric":"Complete with a or an.","question":"I need {{c1::an}} umbrella — it's raining.","choices":[]},
    {"unit":"Unidade 65","rubric":"Complete with a or an.","question":"It was {{c1::a}} difficult decision.","choices":[]},
    {"unit":"Unidade 65","rubric":"Complete with a or an.","question":"He sent {{c1::an}} email this morning.","choices":[]},
    {"unit":"Unidade 65","rubric":"Complete with a or an.","question":"She drives {{c1::a}} hybrid car.","choices":[]},
    {"unit":"Unidade 65","rubric":"Complete with a or an.","question":"It's {{c1::an}} interesting project.","choices":[]},
  ],
  "66": [
    {"unit":"Unidade 66","rubric":"Write the plural form.","question":"one bus → two {{c1::buses}}","choices":[]},
    {"unit":"Unidade 66","rubric":"Write the plural form.","question":"one city → two {{c1::cities}}","choices":[]},
    {"unit":"Unidade 66","rubric":"Write the plural form.","question":"one person → two {{c1::people}}","choices":[]},
    {"unit":"Unidade 66","rubric":"Write the plural form.","question":"one child → two {{c1::children}}","choices":[]},
    {"unit":"Unidade 66","rubric":"Write the plural form.","question":"one woman → two {{c1::women}}","choices":[]},
    {"unit":"Unidade 66","rubric":"Write the plural form.","question":"one potato → two {{c1::potatoes}}","choices":[]},
    {"unit":"Unidade 66","rubric":"Write the plural form.","question":"one leaf → two {{c1::leaves}}","choices":[]},
  ],
  "69": [
    {"unit":"Unidade 69","rubric":"Complete with a, an or the.","question":"I saw {{c1::a}} good film last night. {{c1::The}} film was really interesting.","choices":[]},
    {"unit":"Unidade 69","rubric":"Complete with a, an or the.","question":"She's reading {{c1::a}} book. {{c1::The}} book is a thriller.","choices":[]},
    {"unit":"Unidade 69","rubric":"Complete with a, an or the.","question":"Can I open {{c1::the}} window? It's very hot.","choices":[]},
    {"unit":"Unidade 69","rubric":"Complete with a, an or the.","question":"I need {{c1::an}} umbrella.","choices":[]},
    {"unit":"Unidade 69","rubric":"Complete with a, an or the.","question":"{{c1::The}} sun rises in the east.","choices":[]},
    {"unit":"Unidade 69","rubric":"Complete with a, an or the.","question":"She has {{c1::a}} meeting at 3pm.","choices":[]},
  ],
  "71": [
    {"unit":"Unidade 71","rubric":"Complete with the correct expression — use the where necessary.","question":"She goes {{c1::to work}} by bus every day.","choices":[]},
    {"unit":"Unidade 71","rubric":"Complete with the correct expression — use the where necessary.","question":"I'm going {{c1::home}} early today.","choices":[]},
    {"unit":"Unidade 71","rubric":"Complete with the correct expression — use the where necessary.","question":"Let's go {{c1::to the cinema}} tonight.","choices":[]},
    {"unit":"Unidade 71","rubric":"Complete with the correct expression — use the where necessary.","question":"He goes {{c1::to school}} at 8am.","choices":[]},
    {"unit":"Unidade 71","rubric":"Complete with the correct expression — use the where necessary.","question":"She went {{c1::to hospital}} after the accident.","choices":[]},
    {"unit":"Unidade 71","rubric":"Complete with the correct expression — use the where necessary.","question":"We went {{c1::to the beach}} last weekend.","choices":[]},
  ],
  "72": [
    {"unit":"Unidade 72","rubric":"Complete with the noun — no article for general statements.","question":"I love {{c1::music}} — I listen to it every day.","choices":[]},
    {"unit":"Unidade 72","rubric":"Complete with the noun — no article for general statements.","question":"She hates {{c1::meetings}} — they waste her time.","choices":[]},
    {"unit":"Unidade 72","rubric":"Complete with the noun — no article for general statements.","question":"He drinks {{c1::coffee}} every morning.","choices":[]},
    {"unit":"Unidade 72","rubric":"Complete with the noun — no article for general statements.","question":"Do you like {{c1::chocolate}}?","choices":[]},
    {"unit":"Unidade 72","rubric":"Complete with the noun — no article for general statements.","question":"Most people fear {{c1::failure}}.","choices":[]},
    {"unit":"Unidade 72","rubric":"Complete with the noun — no article for general statements.","question":"Children enjoy {{c1::games}}.","choices":[]},
  ],
  "74": [
    {"unit":"Unidade 74","rubric":"Complete with this, that, these or those.","question":"Can you pass me {{c1::that}} book over there?","choices":[]},
    {"unit":"Unidade 74","rubric":"Complete with this, that, these or those.","question":"{{c1::These}} documents need to be signed today.","choices":[]},
    {"unit":"Unidade 74","rubric":"Complete with this, that, these or those.","question":"{{c1::This}} is my colleague, Sarah.","choices":[]},
    {"unit":"Unidade 74","rubric":"Complete with this, that, these or those.","question":"{{c1::Those}} were difficult times.","choices":[]},
    {"unit":"Unidade 74","rubric":"Complete with this, that, these or those.","question":"I don't like {{c1::this}} idea.","choices":[]},
    {"unit":"Unidade 74","rubric":"Complete with this, that, these or those.","question":"{{c1::That}} was an interesting presentation.","choices":[]},
  ],
  "75": [
    {"unit":"Unidade 75","rubric":"Complete with one or ones.","question":"I need a pen. Have you got {{c1::one}}?","choices":[]},
    {"unit":"Unidade 75","rubric":"Complete with one or ones.","question":"Which shoes do you prefer — the black {{c1::ones}} or the brown {{c1::ones}}?","choices":[]},
    {"unit":"Unidade 75","rubric":"Complete with one or ones.","question":"This laptop is old. I need a new {{c1::one}}.","choices":[]},
    {"unit":"Unidade 75","rubric":"Complete with one or ones.","question":"These reports are outdated. I need the latest {{c1::ones}}.","choices":[]},
    {"unit":"Unidade 75","rubric":"Complete with one or ones.","question":"I don't have a charger. Can I borrow {{c1::one}}?","choices":[]},
  ],
  "76": [
    {"unit":"Unidade 76","rubric":"Complete with some or any.","question":"Can I have {{c1::some}} water, please?","choices":[]},
    {"unit":"Unidade 76","rubric":"Complete with some or any.","question":"I don't have {{c1::any}} time today.","choices":[]},
    {"unit":"Unidade 76","rubric":"Complete with some or any.","question":"She made {{c1::some}} coffee.","choices":[]},
    {"unit":"Unidade 76","rubric":"Complete with some or any.","question":"Are there {{c1::any}} messages for me?","choices":[]},
    {"unit":"Unidade 76","rubric":"Complete with some or any.","question":"I need {{c1::some}} help with this task.","choices":[]},
    {"unit":"Unidade 76","rubric":"Complete with some or any.","question":"We don't have {{c1::any}} meetings this afternoon.","choices":[]},
  ],
  "77": [
    {"unit":"Unidade 77","rubric":"Complete with no, none or not any.","question":"There's {{c1::no}} coffee left.","choices":[]},
    {"unit":"Unidade 77","rubric":"Complete with no, none or not any.","question":"I have {{c1::no}} idea what happened.","choices":[]},
    {"unit":"Unidade 77","rubric":"Complete with no, none or not any.","question":"How many people came? — {{c1::None}}.","choices":[]},
    {"unit":"Unidade 77","rubric":"Complete with no, none or not any.","question":"She has {{c1::no}} experience in this area.","choices":[]},
    {"unit":"Unidade 77","rubric":"Complete with no, none or not any.","question":"I checked my emails but there were {{c1::none}}.","choices":[]},
    {"unit":"Unidade 77","rubric":"Complete with no, none or not any.","question":"We have {{c1::no}} time to waste.","choices":[]},
  ],
  "78": [
    {"unit":"Unidade 78","rubric":"Complete with nobody, nothing, anybody or anything.","question":"{{c1::Nobody}} called while you were out.","choices":[]},
    {"unit":"Unidade 78","rubric":"Complete with nobody, nothing, anybody or anything.","question":"I didn't eat {{c1::anything}} today.","choices":[]},
    {"unit":"Unidade 78","rubric":"Complete with nobody, nothing, anybody or anything.","question":"She told {{c1::nobody}} about the decision.","choices":[]},
    {"unit":"Unidade 78","rubric":"Complete with nobody, nothing, anybody or anything.","question":"Is there {{c1::anything}} I can do to help?","choices":[]},
    {"unit":"Unidade 78","rubric":"Complete with nobody, nothing, anybody or anything.","question":"{{c1::Nothing}} happened at the meeting.","choices":[]},
    {"unit":"Unidade 78","rubric":"Complete with nobody, nothing, anybody or anything.","question":"Did you see {{c1::anybody}} you knew?","choices":[]},
  ],
  "79": [
    {"unit":"Unidade 79","rubric":"Complete with somebody, something, somewhere, nobody, nothing or nowhere.","question":"{{c1::Somebody}} left their laptop in the meeting room.","choices":[]},
    {"unit":"Unidade 79","rubric":"Complete with somebody, something, somewhere, nobody, nothing or nowhere.","question":"There's {{c1::something}} wrong with the server.","choices":[]},
    {"unit":"Unidade 79","rubric":"Complete with somebody, something, somewhere, nobody, nothing or nowhere.","question":"She needs to go {{c1::somewhere}} quiet to concentrate.","choices":[]},
    {"unit":"Unidade 79","rubric":"Complete with somebody, something, somewhere, nobody, nothing or nowhere.","question":"Would you like {{c1::something}} to drink?","choices":[]},
    {"unit":"Unidade 79","rubric":"Complete with somebody, something, somewhere, nobody, nothing or nowhere.","question":"I looked everywhere but found {{c1::nothing}}.","choices":[]},
    {"unit":"Unidade 79","rubric":"Complete with somebody, something, somewhere, nobody, nothing or nowhere.","question":"Can {{c1::somebody}} help me with this?","choices":[]},
  ],
  "80": [
    {"unit":"Unidade 80","rubric":"Complete with every or all.","question":"{{c1::Every}} employee received a bonus.","choices":[]},
    {"unit":"Unidade 80","rubric":"Complete with every or all.","question":"{{c1::All}} the reports were submitted on time.","choices":[]},
    {"unit":"Unidade 80","rubric":"Complete with every or all.","question":"She works {{c1::every}} day, including weekends.","choices":[]},
    {"unit":"Unidade 80","rubric":"Complete with every or all.","question":"{{c1::All}} of us attended the conference.","choices":[]},
    {"unit":"Unidade 80","rubric":"Complete with every or all.","question":"He reads the news {{c1::every}} morning.","choices":[]},
    {"unit":"Unidade 80","rubric":"Complete with every or all.","question":"{{c1::All}} the information is here.","choices":[]},
  ],
  "81": [
    {"unit":"Unidade 81","rubric":"Complete with all, most, some, any or no.","question":"{{c1::Most}} people prefer to work from home.","choices":[]},
    {"unit":"Unidade 81","rubric":"Complete with all, most, some, any or no.","question":"{{c1::All}} the seats are taken.","choices":[]},
    {"unit":"Unidade 81","rubric":"Complete with all, most, some, any or no.","question":"{{c1::Some}} colleagues work part-time.","choices":[]},
    {"unit":"Unidade 81","rubric":"Complete with all, most, some, any or no.","question":"I don't have {{c1::any}} objections.","choices":[]},
    {"unit":"Unidade 81","rubric":"Complete with all, most, some, any or no.","question":"There's {{c1::no}} parking here.","choices":[]},
    {"unit":"Unidade 81","rubric":"Complete with all, most, some, any or no.","question":"{{c1::Most}} meetings are held online now.","choices":[]},
  ],
  "82": [
    {"unit":"Unidade 82","rubric":"Complete with both, either or neither.","question":"{{c1::Both}} candidates are well-qualified.","choices":[]},
    {"unit":"Unidade 82","rubric":"Complete with both, either or neither.","question":"{{c1::Neither}} option is ideal.","choices":[]},
    {"unit":"Unidade 82","rubric":"Complete with both, either or neither.","question":"You can pay by cash or card — {{c1::either}} is fine.","choices":[]},
    {"unit":"Unidade 82","rubric":"Complete with both, either or neither.","question":"{{c1::Both}} systems work, but this one is faster.","choices":[]},
    {"unit":"Unidade 82","rubric":"Complete with both, either or neither.","question":"{{c1::Neither}} of them had the answer.","choices":[]},
    {"unit":"Unidade 82","rubric":"Complete with both, either or neither.","question":"I've been to {{c1::neither}} Paris nor Rome.","choices":[]},
  ],
  "83": [
    {"unit":"Unidade 83","rubric":"Complete with a lot (of), much or many.","question":"She doesn't have {{c1::much}} time.","choices":[]},
    {"unit":"Unidade 83","rubric":"Complete with a lot (of), much or many.","question":"There are {{c1::many}} options to consider.","choices":[]},
    {"unit":"Unidade 83","rubric":"Complete with a lot (of), much or many.","question":"He earns {{c1::a lot of}} money.","choices":[]},
    {"unit":"Unidade 83","rubric":"Complete with a lot (of), much or many.","question":"How {{c1::many}} people attended the event?","choices":[]},
    {"unit":"Unidade 83","rubric":"Complete with a lot (of), much or many.","question":"I don't drink {{c1::much}} coffee.","choices":[]},
    {"unit":"Unidade 83","rubric":"Complete with a lot (of), much or many.","question":"We made {{c1::a lot of}} progress today.","choices":[]},
  ],
  "84": [
    {"unit":"Unidade 84","rubric":"Complete with (a) little or (a) few.","question":"I have {{c1::a few}} minutes to spare.","choices":[]},
    {"unit":"Unidade 84","rubric":"Complete with (a) little or (a) few.","question":"She speaks {{c1::a little}} French.","choices":[]},
    {"unit":"Unidade 84","rubric":"Complete with (a) little or (a) few.","question":"We have very {{c1::little}} time left.","choices":[]},
    {"unit":"Unidade 84","rubric":"Complete with (a) little or (a) few.","question":"There are {{c1::a few}} things to discuss.","choices":[]},
    {"unit":"Unidade 84","rubric":"Complete with (a) little or (a) few.","question":"He has {{c1::few}} friends at work.","choices":[]},
    {"unit":"Unidade 84","rubric":"Complete with (a) little or (a) few.","question":"I need {{c1::a little}} help with this.","choices":[]},
  ],
  "86": [
    {"unit":"Unidade 86","rubric":"Complete with the adverb form of the adjective.","question":"She works very {{c1::quickly}}.","choices":[]},
    {"unit":"Unidade 86","rubric":"Complete with the adverb form of the adjective.","question":"He drives {{c1::badly}} — he had two accidents.","choices":[]},
    {"unit":"Unidade 86","rubric":"Complete with the adverb form of the adjective.","question":"The situation changed {{c1::suddenly}}.","choices":[]},
    {"unit":"Unidade 86","rubric":"Complete with the adverb form of the adjective.","question":"Please speak {{c1::slowly}} — my English isn't perfect.","choices":[]},
    {"unit":"Unidade 86","rubric":"Complete with the adverb form of the adjective.","question":"She sings {{c1::beautifully}}.","choices":[]},
    {"unit":"Unidade 86","rubric":"Complete with the adverb form of the adjective.","question":"He answered the question {{c1::correctly}}.","choices":[]},
  ],
  "91": [
    {"unit":"Unidade 91","rubric":"Complete with enough in the correct position.","question":"She isn't tall {{c1::enough}} to reach the shelf.","choices":[]},
    {"unit":"Unidade 91","rubric":"Complete with enough in the correct position.","question":"Do we have {{c1::enough}} time to finish?","choices":[]},
    {"unit":"Unidade 91","rubric":"Complete with enough in the correct position.","question":"He isn't experienced {{c1::enough}} for the job.","choices":[]},
    {"unit":"Unidade 91","rubric":"Complete with enough in the correct position.","question":"I don't have {{c1::enough}} money to buy a new car.","choices":[]},
    {"unit":"Unidade 91","rubric":"Complete with enough in the correct position.","question":"Is there {{c1::enough}} space in the meeting room?","choices":[]},
    {"unit":"Unidade 91","rubric":"Complete with enough in the correct position.","question":"She's not confident {{c1::enough}} to present.","choices":[]},
  ],
  "92": [
    {"unit":"Unidade 92","rubric":"Complete with too + adjective.","question":"The coffee is {{c1::too hot}} to drink now.","choices":[]},
    {"unit":"Unidade 92","rubric":"Complete with too + adjective.","question":"The bag is {{c1::too heavy}} to carry.","choices":[]},
    {"unit":"Unidade 92","rubric":"Complete with too + adjective.","question":"The report is {{c1::too long}} — please shorten it.","choices":[]},
    {"unit":"Unidade 92","rubric":"Complete with too + adjective.","question":"It's {{c1::too late}} to change the plan now.","choices":[]},
    {"unit":"Unidade 92","rubric":"Complete with too + adjective.","question":"The price is {{c1::too high}} for our budget.","choices":[]},
    {"unit":"Unidade 92","rubric":"Complete with too + adjective.","question":"She's {{c1::too tired}} to continue working.","choices":[]},
  ],
  "93": [
    {"unit":"Unidade 93","rubric":"Put the words in the correct order.","question":"very / speaks / she / well / English → {{c1::She speaks English very well.}}","choices":[]},
    {"unit":"Unidade 93","rubric":"Put the words in the correct order.","question":"very / hard / they / work → {{c1::They work very hard.}}","choices":[]},
    {"unit":"Unidade 93","rubric":"Put the words in the correct order.","question":"every / drives / to / work / day / she → {{c1::She drives to work every day.}}","choices":[]},
    {"unit":"Unidade 93","rubric":"Put the words in the correct order.","question":"well / he / plays / guitar / the / very → {{c1::He plays the guitar very well.}}","choices":[]},
    {"unit":"Unidade 93","rubric":"Put the words in the correct order.","question":"fluently / speaks / she / French → {{c1::She speaks French fluently.}}","choices":[]},
  ],
  "94": [
    {"unit":"Unidade 94","rubric":"Put the frequency adverb in the correct position.","question":"She is late. (always) → {{c1::She is always late.}}","choices":[]},
    {"unit":"Unidade 94","rubric":"Put the frequency adverb in the correct position.","question":"I drink coffee. (usually) → {{c1::I usually drink coffee.}}","choices":[]},
    {"unit":"Unidade 94","rubric":"Put the frequency adverb in the correct position.","question":"He takes the bus. (never) → {{c1::He never takes the bus.}}","choices":[]},
    {"unit":"Unidade 94","rubric":"Put the frequency adverb in the correct position.","question":"They are ready on time. (usually) → {{c1::They are usually ready on time.}}","choices":[]},
    {"unit":"Unidade 94","rubric":"Put the frequency adverb in the correct position.","question":"I check my emails. (often) → {{c1::I often check my emails.}}","choices":[]},
    {"unit":"Unidade 94","rubric":"Put the frequency adverb in the correct position.","question":"She forgets her password. (sometimes) → {{c1::She sometimes forgets her password.}}","choices":[]},
  ],
  "95": [
    {"unit":"Unidade 95","rubric":"Complete with still, yet or already.","question":"I've {{c1::already}} sent the report — it went this morning.","choices":[]},
    {"unit":"Unidade 95","rubric":"Complete with still, yet or already.","question":"Has she arrived {{c1::yet}}?","choices":[]},
    {"unit":"Unidade 95","rubric":"Complete with still, yet or already.","question":"He's {{c1::still}} working — he started at 7am.","choices":[]},
    {"unit":"Unidade 95","rubric":"Complete with still, yet or already.","question":"I haven't finished {{c1::yet}}.","choices":[]},
    {"unit":"Unidade 95","rubric":"Complete with still, yet or already.","question":"She {{c1::still}} hasn't replied to my email.","choices":[]},
    {"unit":"Unidade 95","rubric":"Complete with still, yet or already.","question":"Have you {{c1::already}} seen this film?","choices":[]},
  ],
  "96": [
    {"unit":"Unidade 96","rubric":"Rewrite using a pronoun in the correct position.","question":"Give me the report. → {{c1::Give it to me.}}","choices":[]},
    {"unit":"Unidade 96","rubric":"Rewrite using a pronoun in the correct position.","question":"Send her the file. → {{c1::Send it to her.}}","choices":[]},
    {"unit":"Unidade 96","rubric":"Rewrite using a pronoun in the correct position.","question":"Show me the diagram. → {{c1::Show it to me.}}","choices":[]},
    {"unit":"Unidade 96","rubric":"Rewrite using a pronoun in the correct position.","question":"Pass him the pen. → {{c1::Pass it to him.}}","choices":[]},
    {"unit":"Unidade 96","rubric":"Rewrite using a pronoun in the correct position.","question":"Tell us the answer. → {{c1::Tell it to us.}}","choices":[]},
  ],
  "97": [
    {"unit":"Unidade 97","rubric":"Complete with and, but, or, so or because.","question":"I was tired {{c1::but}} I continued working.","choices":[]},
    {"unit":"Unidade 97","rubric":"Complete with and, but, or, so or because.","question":"She studied hard {{c1::so}} she passed the exam.","choices":[]},
    {"unit":"Unidade 97","rubric":"Complete with and, but, or, so or because.","question":"You can call me {{c1::or}} send an email.","choices":[]},
    {"unit":"Unidade 97","rubric":"Complete with and, but, or, so or because.","question":"He was late {{c1::because}} of the traffic.","choices":[]},
    {"unit":"Unidade 97","rubric":"Complete with and, but, or, so or because.","question":"She likes tea {{c1::and}} coffee.","choices":[]},
    {"unit":"Unidade 97","rubric":"Complete with and, but, or, so or because.","question":"I wanted to help {{c1::but}} I was too busy.","choices":[]},
  ],
  "98": [
    {"unit":"Unidade 98","rubric":"Complete with when.","question":"Call me {{c1::when}} you arrive.","choices":[]},
    {"unit":"Unidade 98","rubric":"Complete with when.","question":"I'll help you {{c1::when}} I finish this.","choices":[]},
    {"unit":"Unidade 98","rubric":"Complete with when.","question":"{{c1::When}} she was a student, she worked part-time.","choices":[]},
    {"unit":"Unidade 98","rubric":"Complete with when.","question":"{{c1::When}} the meeting ends, let's go for lunch.","choices":[]},
    {"unit":"Unidade 98","rubric":"Complete with when.","question":"I'll send the file as soon as it's ready. <br />{{c1::When}} will that be?","choices":[]},
    {"unit":"Unidade 98","rubric":"Complete with when.","question":"{{c1::When}} I was young, I used to play football.","choices":[]},
  ],
  "106": [
    {"unit":"Unidade 106","rubric":"Complete with in, at or on.","question":"She's sitting {{c1::at}} her desk.","choices":[]},
    {"unit":"Unidade 106","rubric":"Complete with in, at or on.","question":"The keys are {{c1::on}} the table.","choices":[]},
    {"unit":"Unidade 106","rubric":"Complete with in, at or on.","question":"He lives {{c1::in}} London.","choices":[]},
    {"unit":"Unidade 106","rubric":"Complete with in, at or on.","question":"We met {{c1::at}} the airport.","choices":[]},
    {"unit":"Unidade 106","rubric":"Complete with in, at or on.","question":"There's a café {{c1::on}} the ground floor.","choices":[]},
    {"unit":"Unidade 106","rubric":"Complete with in, at or on.","question":"She works {{c1::in}} an office in the city centre.","choices":[]},
  ],
  "107": [
    {"unit":"Unidade 107","rubric":"Complete with in, at or on.","question":"I'm waiting {{c1::at}} the bus stop.","choices":[]},
    {"unit":"Unidade 107","rubric":"Complete with in, at or on.","question":"She's {{c1::on}} the bus.","choices":[]},
    {"unit":"Unidade 107","rubric":"Complete with in, at or on.","question":"They're {{c1::at}} a conference in Madrid.","choices":[]},
    {"unit":"Unidade 107","rubric":"Complete with in, at or on.","question":"He's {{c1::in}} bed — he's not well.","choices":[]},
    {"unit":"Unidade 107","rubric":"Complete with in, at or on.","question":"The photo is {{c1::on}} the wall.","choices":[]},
    {"unit":"Unidade 107","rubric":"Complete with in, at or on.","question":"We're {{c1::at}} the top of the building.","choices":[]},
  ],
  "108": [
    {"unit":"Unidade 108","rubric":"Complete with to, in or at.","question":"I'm going {{c1::to}} the office.","choices":[]},
    {"unit":"Unidade 108","rubric":"Complete with to, in or at.","question":"She arrived {{c1::at}} the station at 9am.","choices":[]},
    {"unit":"Unidade 108","rubric":"Complete with to, in or at.","question":"He lives {{c1::in}} Paris.","choices":[]},
    {"unit":"Unidade 108","rubric":"Complete with to, in or at.","question":"We're travelling {{c1::to}} Berlin next week.","choices":[]},
    {"unit":"Unidade 108","rubric":"Complete with to, in or at.","question":"She's staying {{c1::at}} a hotel.","choices":[]},
    {"unit":"Unidade 108","rubric":"Complete with to, in or at.","question":"I'll meet you {{c1::at}} the entrance.","choices":[]},
  ],
  "109": [
    {"unit":"Unidade 109","rubric":"Complete with under, behind, opposite, next to or between.","question":"The café is {{c1::opposite}} the bank.","choices":[]},
    {"unit":"Unidade 109","rubric":"Complete with under, behind, opposite, next to or between.","question":"My bag is {{c1::under}} the desk.","choices":[]},
    {"unit":"Unidade 109","rubric":"Complete with under, behind, opposite, next to or between.","question":"The car is parked {{c1::behind}} the building.","choices":[]},
    {"unit":"Unidade 109","rubric":"Complete with under, behind, opposite, next to or between.","question":"She's standing {{c1::next to}} me.","choices":[]},
    {"unit":"Unidade 109","rubric":"Complete with under, behind, opposite, next to or between.","question":"The supermarket is {{c1::between}} the pharmacy and the school.","choices":[]},
  ],
  "110": [
    {"unit":"Unidade 110","rubric":"Complete with up, over, through, across or along.","question":"She walked {{c1::across}} the street.","choices":[]},
    {"unit":"Unidade 110","rubric":"Complete with up, over, through, across or along.","question":"He ran {{c1::up}} the stairs.","choices":[]},
    {"unit":"Unidade 110","rubric":"Complete with up, over, through, across or along.","question":"We drove {{c1::through}} the tunnel.","choices":[]},
    {"unit":"Unidade 110","rubric":"Complete with up, over, through, across or along.","question":"She jumped {{c1::over}} the fence.","choices":[]},
    {"unit":"Unidade 110","rubric":"Complete with up, over, through, across or along.","question":"They walked {{c1::along}} the river.","choices":[]},
    {"unit":"Unidade 110","rubric":"Complete with up, over, through, across or along.","question":"He climbed {{c1::up}} the ladder.","choices":[]},
  ],
  "111": [
    {"unit":"Unidade 111","rubric":"Complete with the correct preposition.","question":"She's talking {{c1::on}} the phone.","choices":[]},
    {"unit":"Unidade 111","rubric":"Complete with the correct preposition.","question":"I came here {{c1::by}} train.","choices":[]},
    {"unit":"Unidade 111","rubric":"Complete with the correct preposition.","question":"She's married {{c1::to}} a lawyer.","choices":[]},
    {"unit":"Unidade 111","rubric":"Complete with the correct preposition.","question":"I agree {{c1::with}} you on that point.","choices":[]},
    {"unit":"Unidade 111","rubric":"Complete with the correct preposition.","question":"Are you interested {{c1::in}} this project?","choices":[]},
    {"unit":"Unidade 111","rubric":"Complete with the correct preposition.","question":"What are you thinking {{c1::about}}?","choices":[]},
  ],
  "112": [
    {"unit":"Unidade 112","rubric":"Complete with the correct preposition after the adjective.","question":"She's very good {{c1::at}} mathematics.","choices":[]},
    {"unit":"Unidade 112","rubric":"Complete with the correct preposition after the adjective.","question":"He's afraid {{c1::of}} flying.","choices":[]},
    {"unit":"Unidade 112","rubric":"Complete with the correct preposition after the adjective.","question":"I'm interested {{c1::in}} the new project.","choices":[]},
    {"unit":"Unidade 112","rubric":"Complete with the correct preposition after the adjective.","question":"She's tired {{c1::of}} waiting.","choices":[]},
    {"unit":"Unidade 112","rubric":"Complete with the correct preposition after the adjective.","question":"He's responsible {{c1::for}} the entire department.","choices":[]},
    {"unit":"Unidade 112","rubric":"Complete with the correct preposition after the adjective.","question":"Are you happy {{c1::with}} the results?","choices":[]},
  ],
  "113": [
    {"unit":"Unidade 113","rubric":"Complete with the correct preposition after the verb.","question":"Please listen {{c1::to}} me carefully.","choices":[]},
    {"unit":"Unidade 113","rubric":"Complete with the correct preposition after the verb.","question":"Can you look {{c1::at}} this report?","choices":[]},
    {"unit":"Unidade 113","rubric":"Complete with the correct preposition after the verb.","question":"She's waiting {{c1::for}} a reply.","choices":[]},
    {"unit":"Unidade 113","rubric":"Complete with the correct preposition after the verb.","question":"He apologised {{c1::for}} being late.","choices":[]},
    {"unit":"Unidade 113","rubric":"Complete with the correct preposition after the verb.","question":"They arrived {{c1::at}} the office at 9.","choices":[]},
    {"unit":"Unidade 113","rubric":"Complete with the correct preposition after the verb.","question":"I'm thinking {{c1::about}} changing jobs.","choices":[]},
  ],
}

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "custom_exercises.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(EX, f, ensure_ascii=False, indent=2)

print(f"Wrote {sum(len(v) for v in EX.values())} exercises across {len(EX)} units to {out}")
